Project finished.
Daniduran-dev/smashing-magazine pull request #3
Opened 2020-03-13 15:30 UTC by Daniduran-dev

HTML Validator: Passed
Stylelint: Passed

2020-03-13 18:11 UTC, majovanilla requested changes
# Code Review in progress 👀 by Maria Reyes


Hey team, 👋

## You did an *amazing*🌟 ✨ job on this project! 👊🏻  💯

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Improve your Readme file. It should be descriptive of the project. You are using the correct template but now you need to fill it with information about your project. You can add details about what you did in this project, why you did it, how you did it...

- Please write meaningful pull request messages. Check this [example](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

- Check other requirements below.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-03-13 18:11 UTC, majovanilla commented on Readme.md
> +![screenshot](images/screenshot.PNG)
- Improve your Readme file. It should be descriptive of the project. You are using the correct template but now you need to fill it with information about your project. You can add details about what you did in this project, why you did it, how you did it...

2020-03-13 18:11 UTC, majovanilla commented on index.html
> +    </footer>
- The footer should contain centered links. Just change the content to be links as the original page.

2020-03-13 18:11 UTC, majovanilla commented on style.css
> +
You have a repeated styling rules(box-3 and box-4)

2020-03-16 08:05 UTC, uryelah commented
Hello **Daniel Garcia Duran** & **Okiki Apelehin**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all, good job at fixing most of the required changes from the last code review 🎇**

There are still some issues to work through so hang in there 💪 

---------    

### Required changes 🛠 
---------

- [ ] The divs with the `.wrapper-content` class should be `<article>`s. Kindly change them to the semantic tag. You can read more about when to use the[ article tag here.](https://bitsofco.de/sectioning-content-in-html5/)

- [ ] The footer should contain centered links as in the[ original page](https://www.smashingmagazine.com/). Please check the image below for reference,
![Screenshot_2020-03-16 Smashing Magazine — For Web Designers And Developers](https://user-images.githubusercontent.com/16193212/76735383-8defe380-6743-11ea-83d1-87a1fe23651e.png)


- [ ] As the previous TSE mentioned you should add a professional and meaningful PR message as indicated by her link. Check the gif below for an example.
![69548761-3a8d3600-0f98-11ea-9f19-14da361c12e2](https://user-images.githubusercontent.com/16193212/76735347-7add1380-6743-11ea-9811-dc2e47731f52.gif)

- [ ] This is a design tear down and not a clone, please remove the icons or any color that you have in the site. You can represent them with grey divs. The idea is to represent the visual weight they have in the site visual hierarchy, color disrupts that as it calls too much attention to itself when around grey areas.

----

**Kindly fix the REQUIRED above issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-03-16 09:19 UTC, uryelah commented
Hey guys, good work fixing the issgin article tags and icons.

You are still missing two required changes above.

They are: 

### Required changes 🛠 
---------

- [ ] The footer should contain centered links as in the[ original page](https://www.smashingmagazine.com/). Please check the image below for reference,
![Screenshot_2020-03-16 Smashing Magazine — For Web Designers And Developers](https://user-images.githubusercontent.com/16193212/76735383-8defe380-6743-11ea-83d1-87a1fe23651e.png)

- [ ] As the previous TSE mentioned you should add a professional and meaningful PR message as indicated by her link. Check the gif below for an example.
![69548761-3a8d3600-0f98-11ea-9f19-14da361c12e2](https://user-images.githubusercontent.com/16193212/76735347-7add1380-6743-11ea-9811-dc2e47731f52.gif)

----

**Kindly fix the all REQUIRED above issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-03-16 10:28 UTC, lekegitrepo commented
### Hi @Daniduran-dev and @okikiola11, you have done a good job.
### This project is approved. Good luck with the next project.

**_Note: Please try fix to the merge conflict before submitting for review._**

### Review by: Temitayo Adeleke

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

2020-03-16 10:28 UTC, lekegitrepo approved these changes
### Status: Approved

2020-03-16 11:23 UTC, merged